# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0003_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='neighborhood_id',
            field=models.ForeignKey(blank=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='neighbor.Neighborhood'),
            preserve_default=False,
        ),
    ]
