# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0004_auto_20190325_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='neighborhood_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbor.Neighborhood'),
        ),
    ]
